# Generated by Django 4.0.4 on 2022-05-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_klient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klient',
            name='dataUr',
        ),
    ]
