# Generated by Django 4.0.4 on 2022-05-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_klient_dataur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='wiek',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
